services:
  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bench-network
      - mariadb-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.adminer.loadbalancer.server.port=8080
      - traefik.http.routers.adminer-http.service=adminer
      - traefik.http.routers.adminer-http.entrypoints=http
      - traefik.http.routers.adminer-http.rule=Host(`dbmanager.app.charismaindustrial.com`) || Host(`www.dbmanager.app.charismaindustrial.com`)
      # adminer-http to use the middleware to redirect to https
      - traefik.http.routers.adminer-http.middlewares=https-redirect
      # adminer-https the actual router using HTTPS
      # Uses the environment variable SITES_RULE
      - traefik.http.routers.adminer-https.rule=Host(`dbmanager.app.charismaindustrial.com`) || Host(`www.dbmanager.app.charismaindustrial.com`)
      - traefik.http.routers.adminer-https.entrypoints=https
      - traefik.http.routers.adminer-https.tls=true
      # Use the service adminer with the frontend
      - traefik.http.routers.adminer-https.service=adminer
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.adminer-https.tls.certresolver=le
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DEFAULT_SERVER: db
